application: affable-ruler-94808 
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:

- url: /stage1
  static_dir: Stage12

- url: /stage2
  static_dir: Stage12
 
- url: /stage3
  static_dir: Stage3

- url: /css
  static_dir: css
 
- url: /images
  static_dir: images
  
- url: /js
  static_dir: js
  
- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /fizzbuzz.*
  script: fizzbuzz.app  

- url: /guestbook.*
  script: guestbook.app
  
- url: /addcontent.*
  script: addcontent.app  
  
- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "latest"
- name: jinja2
  version: latest  
